server:
  port: 8808
  servlet:
    context-path:
  tomcat:
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/stupid?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 30000
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5000
mybatis:
  #  classpath:/com/*/*/mapper/*Mapper.xml 放在resources目录下classpath:/mapper/**.xml
  mapper-locations: classpath*:/mapper/**.xml
  configuration:
    # 启动结果集自动映射（NONE,PARTIAL,FULL）
    auto-mapping-behavior: partial
    # 驼峰映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
logging:
  config: classpath:logback-spring.xml
log:
  level: INFO
cache:
  type:
    local: guava
    distribute: redis
distribute:
  type:
    enable: true
    # single or cluster
    arrange: single
    lock: redisson
    semaphore: redisson